### ISSUE TITLE
TODO - Collect the ideas from status file

### ISSUE THREAD

**Issue by ret394** [ret394/jubilant-broccoli#55]
https://github.com/ret394/jubilant-broccoli/blob/master/status/current%20status.txt

**Comment by ret394** [comment]
> Programming Language Jam $10,000 grand prize
> ended in Aug

Great! :-(

**Comment by aristotle73** [comment]
how to contact you? are you offline?
i'm new here.

**Comment by aristotle73** [comment]
@ret394, you can still apologize, and I will not report you.

**Comment by aristotle73** [comment]
@ret394, you can still apologize, and I will not report you.

**Comment by aristotle73** [comment]
@ret394, you can still apologize, and I will not report you. Though you do not use correct skin tone emojis. And maybe a racist pig.

Just wondering, who do you think you should vote for. Biden or Trump?

**Comment by ret394** [comment]
https://github.com/aristotle73 said -

> 
> 
> how to contact you? are you offline?
> i'm new here.




> 
> 
> @ret394, you can still apologize, and I will not report you.



> 
> 
> @ret394, you can still apologize, and I will not report you.



> 
> 
> @ret394, you can still apologize, and I will not report you. Though you do not use correct skin tone emojis, I have evidence. And maybe a racist pig.
> 
> Just wondering, who do you think you will vote for. Biden or Trump?
