### ISSUE TITLE
migrate from https://gitter.im/rust-lang/rust

### ISSUE THREAD

**Issue by ret394** [ret394/jubilant-broccoli#7]

**Comment by ret394** [comment]
@ret394
 > ```rust
> foo<'a>
> foo<'a, 'b>
> ```
> 
> can this syntax be changed? seems like skeuomorphism in language design. ignoring others that make this error. its better, less confusing with 
> 
> ```
> foo: a
> ``` 
> more so if  consistent across programming languages.
>

**Comment by ret394** [comment]
@tanriol 

> @ret394 What do you expect the syntax you're suggesting to do?

**Comment by ret394** [comment]
@ret394 
> first k:v pair is not confusing. please think some more about the second.
>

**Comment by ret394** [comment]
@tanriol 
> When you write `foo<'a>`, this is usually a generic function with a lifetime generic parameter `'a`. It definitely does not inherit anything from that parameter :-)
> It can also be a type (tuple / struct / enum / union) with the same parameter, but again, it does not inherit anything from that parameter. It can be limited to "lives no longer than this lifetime"... or can be not limited in that way.

**Comment by ret394** [comment]
@Ichoran 
> @ret394 - I'm confused about what you're confused about :joy:  What do you think `foo: a` should mean?  How are we supposed to understand `foo: a` when we already have `instance: Type` in many cases (and proposals to include it more broadly), e.g. `let x: f32 = 2.7`.

**Comment by ret394** [comment]
@tanriol 
> @ret394 Okay, let's go to some concrete example
> ```rust
> fn do_clone<'a, T: Clone>(arg: &'a T) -> T { ... }
> ```
> how would you write this in your syntax?

**Comment by ret394** [comment]
@ret394  
> do you mind moving this conversation to github issues(https://github.com/ret394/jubilant-broccoli); tedious to follow the chain of comments.
>

**Comment by ret394** [comment]
@tanriol

@ret394 Sure, you can move it there.

**Comment by ret394** [comment]
> ```rust
> foo<'a>
> foo<'a, 'b>
> ```

was copied from https://doc.rust-lang.org/stable/rust-by-example/scope/lifetime/explicit.html
I messed up that entire post. Extremely sorry about that.

**Comment by ret394** [comment]
`fn do_clone<'a, T: Clone>(arg: &'a T) -> T { ... }`
can be
`fn do_clone('a, T: Clone)(arg: &'a T) -> T { ... }`

**Comment by tanriol** [comment]
I'd say that makes it much less clear as now the two pairs of parentheses enclose completely different things. Also, why would that be better than the original version?
